// src/domain/curriculum/kindergarten/alphabetStandards.js
// Definitive A-Z Alphabet & Phonics Source of Truth based on Core Knowledge CKLA & Orton-Gillingham
// Contains: Letter Name, Phonetic Sound, Articulatory Mouth Cue, 3-Line Stroke Chant, Starting Dot, Anchor Words
// Created: 2026-09-27

export const ALPHABET_A_TO_Z = {
  a: {
    letter: "A",
    lowercase: "a",
    sound: "/æ/ (short a)",
    mouthCue: "Open mouth wide like you are taking a big bite of an apple, tongue flat on the bottom.",
    strokeChant: "Start at the 2 o'clock dot on the dashed midline. Curve up and around to the baseline, push straight up to the midline, and pull straight down to the baseline.",
    starterDot: "midline",
    anchorWord: "apple",
    anchorEmoji: "🍎",
    alliteration: "Annie alligator eats red apples.",
    sampleWords: ["at", "am", "an", "ant", "ax"]
  },
  b: {
    letter: "B",
    lowercase: "b",
    sound: "/b/",
    mouthCue: "Press your lips together gently, then pop them open with a quick voiced burst.",
    strokeChant: "Start at the top headline. Pull straight down to the baseline, bounce halfway up to the dashed midline, and curve around to the baseline.",
    starterDot: "headline",
    anchorWord: "bear",
    anchorEmoji: "🐻",
    alliteration: "Big brown bear bounces a ball.",
    sampleWords: ["bat", "bed", "big", "box", "bug"]
  },
  c: {
    letter: "C",
    lowercase: "c",
    sound: "/k/ (hard c)",
    mouthCue: "Open mouth slightly, raise the back of your tongue to touch the roof of your mouth, and push air out with a dry click.",
    strokeChant: "Start just below the dashed midline. Curve up and around to the baseline, and smile up like an open circle.",
    starterDot: "midline",
    anchorWord: "cat",
    anchorEmoji: "🐱",
    alliteration: "Clever cat catches a crunchy carrot.",
    sampleWords: ["cat", "can", "cap", "cup", "cot"]
  },
  d: {
    letter: "D",
    lowercase: "d",
    sound: "/d/",
    mouthCue: "Tap the tip of your tongue behind your top front teeth, and drop it down with a tap of voice.",
    strokeChant: "Start at the dashed midline. Curve around like a 'c' to the baseline, push ALL the way up to the top headline, and pull straight down to the baseline.",
    starterDot: "midline",
    anchorWord: "dog",
    anchorEmoji: "🐶",
    alliteration: "Dizzy dog digs in the dirt.",
    sampleWords: ["dad", "dig", "dot", "duck", "den"]
  },
  e: {
    letter: "E",
    lowercase: "e",
    sound: "/ɛ/ (short e)",
    mouthCue: "Smile slightly with mouth halfway open, tongue raised slightly in the middle like saying 'eh'.",
    strokeChant: "Start between the dashed midline and baseline. Push a straight line across, curve up and around the midline, and slide to the baseline.",
    starterDot: "middle-space",
    anchorWord: "egg",
    anchorEmoji: "🥚",
    alliteration: "Eddie elephant exercises early.",
    sampleWords: ["egg", "elf", "elk", "end", "exit"]
  },
  f: {
    letter: "F",
    lowercase: "f",
    sound: "/f/",
    mouthCue: "Bite your bottom lip gently with your top teeth and blow air out like a soft breeze.",
    strokeChant: "Start just below the top headline. Curve up and over like a candy cane, pull straight down to the baseline, and cross at the dashed midline.",
    starterDot: "headline",
    anchorWord: "fish",
    anchorEmoji: "🐟",
    alliteration: "Funny fast fish floats in fresh water.",
    sampleWords: ["fan", "fit", "fog", "fox", "fun"]
  },
  g: {
    letter: "G",
    lowercase: "g",
    sound: "/g/ (hard g)",
    mouthCue: "Touch the back of your tongue to the roof of your mouth, let the voice burble in your throat as you drop it: /g/ /g/.",
    strokeChant: "Start at the dashed midline. Curve around to the baseline like a 'c', push up to the midline, pull straight down below the baseline, and hook like a fishhook.",
    starterDot: "midline",
    anchorWord: "grapes",
    anchorEmoji: "🍇",
    alliteration: "Green grasshopper greets garden goose.",
    sampleWords: ["gas", "get", "got", "gum", "gap"]
  },
  h: {
    letter: "H",
    lowercase: "h",
    sound: "/h/",
    mouthCue: "Open mouth relaxed and breathe out warm air onto your hand like checking your breath.",
    strokeChant: "Start at the top headline. Pull straight down to the baseline, bounce back up to the dashed midline, and make a tall hump down to the baseline.",
    starterDot: "headline",
    anchorWord: "hat",
    anchorEmoji: "🎩",
    alliteration: "Happy horse hops high.",
    sampleWords: ["hat", "hen", "hit", "hot", "hut"]
  },
  i: {
    letter: "I",
    lowercase: "i",
    sound: "/ɪ/ (short i)",
    mouthCue: "Slight smile, chin relaxed, voice makes an itchy squeak: /ih/ /ih/ like an itchy insect.",
    strokeChant: "Start at the dashed midline. Pull straight down to the baseline. Lift pencil and add one neat dot floating above the midline.",
    starterDot: "midline",
    anchorWord: "igloo",
    anchorEmoji: "🧊",
    alliteration: "Inky iguana is in the igloo.",
    sampleWords: ["in", "it", "is", "ill", "ink"]
  },
  j: {
    letter: "J",
    lowercase: "j",
    sound: "/dʒ/",
    mouthCue: "Pucker lips like a little beak, touch tongue to roof of mouth, and burst forward with voice: /j/ /j/.",
    strokeChant: "Start at the dashed midline. Pull straight down past the baseline, curve left like a fishhook, and add a neat dot floating above the midline.",
    starterDot: "midline",
    anchorWord: "jar",
    anchorEmoji: "🫙",
    alliteration: "Jolly jellyfish jumps for juicy jam.",
    sampleWords: ["jam", "jet", "jig", "jog", "jug"]
  },
  k: {
    letter: "K",
    lowercase: "k",
    sound: "/k/",
    mouthCue: "Same sound as hard C: raise back of tongue and release a sharp burst of air.",
    strokeChant: "Start at the top headline. Pull straight down to the baseline. Pick up pencil, slide in from the dashed midline to the center, and kick a leg out to the baseline.",
    starterDot: "headline",
    anchorWord: "kite",
    anchorEmoji: "🪁",
    alliteration: "Kind king kisses playful kitten.",
    sampleWords: ["kid", "kit", "kin", "keg", "kick"]
  },
  l: {
    letter: "L",
    lowercase: "l",
    sound: "/l/",
    mouthCue: "Place the flat tip of your tongue behind your top front teeth and hum with your voice: /lll/.",
    strokeChant: "Start at the top headline. Pull straight down like a tall soldier, stopping right at the baseline.",
    starterDot: "headline",
    anchorWord: "lion",
    anchorEmoji: "🦁",
    alliteration: "Little lazy lion licks lovely lollipop.",
    sampleWords: ["lap", "leg", "lip", "log", "luck"]
  },
  m: {
    letter: "M",
    lowercase: "m",
    sound: "/m/",
    mouthCue: "Press your lips firmly together, keep teeth slightly apart, and hum through your nose like delicious food: /mmm/.",
    strokeChant: "Start at the dashed midline. Pull straight down to the baseline, bounce up to the midline and hump over to the baseline, bounce up again and hump over to the baseline.",
    starterDot: "midline",
    anchorWord: "monkey",
    anchorEmoji: "🐵",
    alliteration: "Many merry monkeys munch sweet mangos.",
    sampleWords: ["mat", "men", "mop", "mud", "map"]
  },
  n: {
    letter: "N",
    lowercase: "n",
    sound: "/n/",
    mouthCue: "Touch the tip of your tongue to the roof of your mouth behind your top teeth, lips open, voice hums through nose: /nnn/.",
    strokeChant: "Start at the dashed midline. Pull straight down to the baseline, bounce up to the midline and hump over to the baseline.",
    starterDot: "midline",
    anchorWord: "nest",
    anchorEmoji: "🪺",
    alliteration: "Nine nice newts nap in a warm nest.",
    sampleWords: ["net", "nod", "nut", "nap", "nip"]
  },
  o: {
    letter: "O",
    lowercase: "o",
    sound: "/ɒ/ (short o)",
    mouthCue: "Open mouth round like an oval at the doctor's office saying 'ahhh' with tongue resting low.",
    strokeChant: "Start at the 2 o'clock dot on the dashed midline. Curve around to the baseline, and close it back up at the top.",
    starterDot: "midline",
    anchorWord: "octopus",
    anchorEmoji: "🐙",
    alliteration: "Oliver octopus opens orange oysters.",
    sampleWords: ["on", "off", "ox", "odd", "otter"]
  },
  p: {
    letter: "P",
    lowercase: "p",
    sound: "/p/",
    mouthCue: "Press lips together, blow a tiny puff of air with NO voice, like blowing out a candle: /p/ /p/.",
    strokeChant: "Start at the dashed midline. Pull straight down below the baseline into the cellar, bounce back up to the midline, and curve around to the baseline.",
    starterDot: "midline",
    anchorWord: "pig",
    anchorEmoji: "🐷",
    alliteration: "Playful pink pig paints purple pumpkins.",
    sampleWords: ["pan", "pet", "pin", "pot", "pup"]
  },
  q: {
    letter: "Q",
    lowercase: "q",
    sound: "/kw/ (buddy letters 'qu')",
    mouthCue: "Round lips and release air with a quick double sound /k/-/w/ like a duck saying quack.",
    strokeChant: "Start at the dashed midline. Curve around like an 'a', pull straight down below the baseline, and flick a little kick back up.",
    starterDot: "midline",
    anchorWord: "queen",
    anchorEmoji: "👑",
    alliteration: "Quiet queen quilt quickly.",
    sampleWords: ["quack", "quit", "quick", "quiz"]
  },
  r: {
    letter: "R",
    lowercase: "r",
    sound: "/r/",
    mouthCue: "Curl the sides of your tongue against your top back teeth, make a growl like a friendly engine: /rrr/.",
    strokeChant: "Start at the dashed midline. Pull straight down to the baseline, bounce up toward the midline, and curve over like a little branch.",
    starterDot: "midline",
    anchorWord: "rabbit",
    anchorEmoji: "🐰",
    alliteration: "Red runner rabbit races across rocks.",
    sampleWords: ["rat", "red", "rip", "rod", "run"]
  },
  s: {
    letter: "S",
    lowercase: "s",
    sound: "/s/",
    mouthCue: "Teeth close together, smile, and hiss air out the front like a snake: /sss/.",
    strokeChant: "Start just below the dashed midline. Curve back and over the top, slither down and forward, and curve back along the baseline.",
    starterDot: "midline",
    anchorWord: "sun",
    anchorEmoji: "☀️",
    alliteration: "Silly smiling snake slides on sand.",
    sampleWords: ["sad", "set", "sit", "sob", "sun"]
  },
  t: {
    letter: "T",
    lowercase: "t",
    sound: "/t/",
    mouthCue: "Tap tongue tip behind top teeth, release a tiny crisp puff of air with no voice like a ticking clock: /t/ /t/.",
    strokeChant: "Start at the top headline. Pull straight down to the baseline. Lift pencil and cross right on the dashed midline from left to right.",
    starterDot: "headline",
    anchorWord: "turtle",
    anchorEmoji: "🐢",
    alliteration: "Tiny turtle taps two tired toes.",
    sampleWords: ["tap", "ten", "tip", "top", "tub"]
  },
  u: {
    letter: "U",
    lowercase: "u",
    sound: "/ʌ/ (short u)",
    mouthCue: "Relax jaw open halfway, make an open tummy sound like you got bumped gently: /uh/ /uh/.",
    strokeChant: "Start at the dashed midline. Pull down to the baseline, curve up like a cup to the midline, and pull straight down to the baseline.",
    starterDot: "midline",
    anchorWord: "umbrella",
    anchorEmoji: "☂️",
    alliteration: "Uncle upside umbrella under trees.",
    sampleWords: ["up", "us", "under", "ugly", "umpire"]
  },
  v: {
    letter: "V",
    lowercase: "v",
    sound: "/v/",
    mouthCue: "Rest top teeth on bottom lip like /f/, but turn your voice motor ON so your lip tickles: /vvv/.",
    strokeChant: "Start at the dashed midline. Slant down to the baseline, and slant right back up to the dashed midline.",
    starterDot: "midline",
    anchorWord: "volcano",
    anchorEmoji: "🌋",
    alliteration: "Violet vulture visits vibrant volcano.",
    sampleWords: ["van", "vet", "vat", "vine", "vote"]
  },
  w: {
    letter: "W",
    lowercase: "w",
    sound: "/w/",
    mouthCue: "Pucker lips tight into an 'O' shape, voice turns on and lips glide open: /w/ /w/.",
    strokeChant: "Start at the dashed midline. Slant down to the baseline, slant up to midline, slant down to baseline, and slant up to midline.",
    starterDot: "midline",
    anchorWord: "watermelon",
    anchorEmoji: "🍉",
    alliteration: "Warm windy walrus washes sweet watermelon.",
    sampleWords: ["web", "wet", "win", "wig", "wag"]
  },
  x: {
    letter: "X",
    lowercase: "x",
    sound: "/ks/",
    mouthCue: "Combine /k/ and /s/ together in a quick burst: /ks/ like at the end of box.",
    strokeChant: "Start at the dashed midline. Slant down to the right to the baseline. Pick up pencil, start at midline on right, and slant down across to the left.",
    starterDot: "midline",
    anchorWord: "fox (final sound)",
    anchorEmoji: "🦊",
    alliteration: "Six clever foxes fix a box.",
    sampleWords: ["box", "fox", "six", "mix", "wax"]
  },
  y: {
    letter: "Y",
    lowercase: "y",
    sound: "/j/",
    mouthCue: "Sides of tongue touch top teeth, lips wide, voice glides open: /y/ /y/ like yummy.",
    strokeChant: "Start at the dashed midline. Slant down to the baseline. Pick up pencil, start at midline on right, slant down through the baseline into the cellar.",
    starterDot: "midline",
    anchorWord: "yarn",
    anchorEmoji: "🧶",
    alliteration: "Young yellow yak yawns with yellow yarn.",
    sampleWords: ["yak", "yam", "yes", "yet", "yell"]
  },
  z: {
    letter: "Z",
    lowercase: "z",
    sound: "/z/",
    mouthCue: "Teeth close together, smile like /s/, but turn your voice buzzer ON so it buzzes like a bee: /zzz/.",
    strokeChant: "Start at the dashed midline. Slide across to the right, slant down to the baseline on the left, and slide across the baseline to the right.",
    starterDot: "midline",
    anchorWord: "zebra",
    anchorEmoji: "🦓",
    alliteration: "Zippy zebra zips around the zoo.",
    sampleWords: ["zap", "zip", "zoo", "zone", "zero"]
  }
};
